DATASET: 
  TRAIN_DATA_PATH: datasets/interim/poly_4_2_1_4-train-nonrigid.pk
  VAL_DATA_PATH: datasets/interim/poly_4_2_1_4-val-nonrigid.pk
  TEST_DATA_PATH: datasets/interim/poly_4_2_1_4-test-nonrigid.pk
  NORMALIZE: std 

MODEL:
  ACTIVATION: SiLU
  HIDDEN_DIMS: [384, 384]

LOSS:
  NAME: WRMSE
  WEIGHT_TYPE: Ratio

REGULARIZATION:
  NAME: L1
  LAMBDA: 5.0e-7

TRAINING:
  MAX_EPOCHS: 10000 
  OPTIMIZER:
    NAME: LBFGS
    LR: 1.0
    TOLERANCE_GRAD: 1.0e-14
    TOLERANCE_CHANGE: 1.0e-14
  SCHEDULER:
    NAME: ReduceLROnPlateau
    LR_REDUCE_GAMMA: 0.8
    PATIENCE: 400 
    THRESHOLD: 0.1
    THRESHOLD_MODE: abs
    COOLDOWN: 10
    MIN_LR: 1.0e-5
  EARLY_STOPPING:
    PATIENCE: 2000 
    TOLERANCE: 0.05

OUTPUT_PATH: models/nonrigid/L2/L2-6-L1
